### PR TITLE
perf: use `uniseg.StringWidth`

### PR DESCRIPTION
**Pull request by maaslalani**
Use `uniseg.StringWidth` for performance.

### CODE REVIEW

**Comment by maaslalani** [comment]
NB: We're upgrading from 1.11 to 1.18, which is a sizeable jump.

**Review by mikelorant — APPROVED** [review]

**Comment by muesli** [comment]
Looks good to me, but we should do this across all sub-packages.

**Comment by mikelorant** [comment]
For reference, the remaining functions have been updated in pull request #71.

**Comment by maaslalani** [comment]
Ah sorry looks like this PR closed due to me deleting my fork.

**Pull request closed without merging**
